=== sam-hunt/food-portions/src/fps.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="foodPortionSizes">
	  	<xs:complexType>
	    	<xs:sequence>
	    		<xs:element name="photo" maxOccurs="unbounded">
	    			<xs:complexType>
	    				<xs:sequence>
				      		<xs:element name="photoGuideCode" type="xs:string" />
							<xs:element name="photoNumber" type="xs:integer" />
							<xs:element name="photoFilename" type="xs:string" />
							<xs:element name="photoDescription" type="xs:string" />
							<xs:element name="photoItem" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="inPhotoCode" type="xs:string" />
										<xs:element name="atlasNumber" type="xs:integer" minOccurs="0" />
										<xs:element name="itemDescription" type="xs:string" />
										<xs:element name="weight" minOccurs="0">
										  	<xs:complexType>
										    	<xs:simpleContent>
										      		<xs:extension base="xs:nonNegativeInteger">
										        		<xs:attribute name="units" type="xs:string" default="g"/>
										      		</xs:extension>
										    	</xs:simpleContent>
										  	</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
	    	</xs:sequence>
	  	</xs:complexType>
	</xs:element>
</xs:schema>

=== sam-hunt/food-portions/src/fps.xml
<?xml version="1.0" encoding="UTF-8"?>
<foodPortionSizes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="fps.xsd">
	<photo>
		<photoGuideCode>G1</photoGuideCode>
		<photoNumber>79</photoNumber>
		<photoFilename>79_G1.jpg</photoFilename>
		<photoDescription>Bread Slice Selection</photoDescription>
		<photoItem>
			<inPhotoCode>A </inPhotoCode>
			<atlasNumber>1</atlasNumber>
			<itemDescription>Whole grain bloomer small</itemDescription>
			<weight units="g">27</weight>
		</photoItem>
		<photoItem>
			<inPhotoCode>B </inPhotoCode>
			<atlasNumber>2</atlasNumber>
			<itemDescription>Whole grain bloomer large</itemDescription>
			<weight units="g">33</weight>
		</photoItem>
		<photoItem>
			<inPhotoCode>C</inPhotoCode>
			<atlasNumber>3</atlasNumber>
			<itemDescription>White crusty bloomer small</itemDescription>
			<weight units="g">20</weight>
		</photoItem>
		<photoItem>
			<inPhotoCode>D </inPhotoCode>
			<atlasNumber>4</atlasNumber>
			<itemDescription>White crusty bloomer large</itemDescription>
			<weight units="g">23</weight>
		</photoItem>
		<photoItem>
			<inPhotoCode>E </inPhotoCode>
			<atlasNumber>5</atlasNumber>
			<itemDescription>Wholemeal unsliced small</itemDescription>
			<weight units="g">30</weight>
		</photoItem>
		<photoItem>
			<inPhotoCode>F </inPhotoCode>
			<atlasNumber>6</atlasNumber>
			<itemDescription>Wholemeal unsliced large</itemDescription>
			<weight units="g">38</weight>
		</photoItem>
		<photoItem>
			<inPhotoCode>G </inPhotoCode>
			<atlasNumber>7</atlasNumber>
			<itemDescription>Soda bread</itemDescription>
			<weight units="g">20</weight>
		</photoItem>
		<photoItem>
			<inPhotoCode>H </inPhotoCode>
			<atlasNumber>8</atlasNumber>
			<itemDescription>Soda bread</itemDescription>
			<weight units="g">32</weight>
		</photoItem>
		<photoItem>
			<inPhotoCode>I </inPhotoCode>
			<atlasNumber>9</atlasNumber>
			<itemDescription>White sliced small</itemDescription>
			<weight units="g">25</weight>
		</photoItem>
		<photoItem>
			<inPhotoCode>J </inPhotoCode>
			<atlasNumber>10</atlasNumber>
			<itemDescription>White sliced large</itemDescription>
			<weight units="g">36</weight>
		</photoItem>
		<photoItem>
			<inPhotoCode>K </inPhotoCode>
			<atlasNumber>11</atlasNumber>
			<itemDescription>White sliced large</itemDescription>
			<weight units="g">36</weight>
		</photoItem>
		<photoItem>
			<inPhotoCode>L </inPhotoCode>
			<atlasNumber>12</atlasNumber>
			<itemDescription>Wholemeal sliced small</itemDescription>
			<weight units="g">25</weight>
		</photoItem>
		<photoItem>
			<inPhotoCode>M </inPhotoCode>
			<atlasNumber>13</atlasNumber>
			<itemDescription>Wholemeal sliced large</itemDescription>
			<weight units="g">36</weight>
		</photoItem>
		<photoItem>
			<inPhotoCode>N </inPhotoCode>
			<atlasNumber>14</atlasNumber>
			<itemDescription>Light rye bread</itemDescription>
			<weight units="g">17</weight>
		</photoItem>
		<photoItem>
			<inPhotoCode>O</inPhotoCode>
			<atlasNumber>15</atlasNumber>
			<itemDescription>French stick 6" piece</itemDescription>
			<weight units="g">120</weight>
		</photoItem>
		<photoItem>
			<inPhotoCode>p </inPhotoCode>
			<atlasNumber>16</atlasNumber>
			<itemDescription>French stick 2" piece</itemDescription>
			<weight units="g">40</weight>
		</photoItem>
	</photo>
	
	<photo>
		<photoGuideCode>G2</photoGuideCode>
		<photoNumber>80</photoNumber>
		<photoFilename>80_G2.jpg</photoFilename>
		<photoDescription>Bread Rolls</photoDescription>
		<photoItem>
			<inPhotoCode>A </inPhotoCode>
			<atlasNumber>1</atlasNumber>
			<itemDescription>White crusty pain</itemDescription>
			<weight units="g">55</weight>
		</photoItem>
		<photoItem>
			<inPhotoCode>B </inPhotoCode>
			<atlasNumber>2</atlasNumber>
			<itemDescription>White petit pain</itemDescription>
			<weight units="g">46</weight>
		</photoItem>
		<photoItem>
			<inPhotoCode>C</inPhotoCode>
			<atlasNumber>3</atlasNumber>
			<itemDescription>White bap soft</itemDescription>
			<weight units="g">58</weight>
		</photoItem>
		<photoItem>
			<inPhotoCode>D </inPhotoCode>
			<atlasNumber>4</atlasNumber>
			<itemDescription>White Vienna crusty</itemDescription>
			<weight units="g">60</weight>
		</photoItem>
		<photoItem>
			<inPhotoCode>E </inPhotoCode>
			<atlasNumber>5</atlasNumber>
			<itemDescription>White finger roll</itemDescription>
			<weight units="g">41</weight>
		</photoItem>
		<photoItem>
			<inPhotoCode>F </inPhotoCode>
			<atlasNumber>6</atlasNumber>
			<itemDescription>White bridge roll</itemDescription>
			<weight units="g">30</weight>
		</photoItem>
		<photoItem>
			<inPhotoCode>G </inPhotoCode>
			<atlasNumber>7</atlasNumber>
			<itemDescription>Brown soft bap</itemDescription>
			<weight units="g">55</weight>
		</photoItem>
		<photoItem>
			<inPhotoCode>H </inPhotoCode>
			<atlasNumber>8</atlasNumber>
			<itemDescription>Oatmeal soft</itemDescription>
			<weight units="g">60</weight>
		</photoItem>
		<photoItem>
			<inPhotoCode>I </inPhotoCode>
			<atlasNumber>9</atlasNumber>
			<itemDescription>White crusty bap</itemDescription>
			<weight units="g">51</weight>
		</photoItem>
		<photoItem>
			<inPhotoCode>J </inPhotoCode>
			<atlasNumber>10</atlasNumber>
			<itemDescription>White floury batch</itemDescription>
			<weight units="g">65</weight>
		</photoItem>
		<photoItem>
			<inPhotoCode>K </inPhotoCode>
			<atlasNumber>11</atlasNumber>
			<itemDescription>Bagel</itemDescription>
			<weight units="g">76</weight>
		</photoItem>
		<photoItem>
			<inPhotoCode>L </inPhotoCode>
			<atlasNumber>12</atlasNumber>
			<itemDescription>New York style bagel</itemDescription>
			<weight units="g">80</weight>
		</photoItem>
		<photoItem>
			<inPhotoCode>M </inPhotoCode>
			<atlasNumber>13</atlasNumber>
			<itemDescription>Hamburger bun</itemDescription>
			<weight units="g">71</weight>
		</photoItem>
		<photoItem>
			<inPhotoCode>N </inPhotoCode>
			<atlasNumber>14</atlasNumber>
			<itemDescription>(rusty granary</itemDescription>
			<weight units="g">54</weight>
		</photoItem>
		<photoItem>
			<inPhotoCode>O</inPhotoCode>
			<atlasNumber>15</atlasNumber>
			<itemDescription>Hovis 'mini' loaf</itemDescription>
			<weight units="g">35</weight>
		</photoItem>
	</photo>
	
	<photo>
		<photoGuideCode>G3</photoGuideCode>
		<photoNumber>81</photoNumber>
		<photoFilename>81_G3.jpg</photoFilename>
		<photoDescription>Pizza</photoDescription>
		<photoItem>
			<inPhotoCode>A </inPhotoCode>
			<atlasNumber>1</atlasNumber>
			<itemDescription>Mini pizza thin base</itemDescription>
			<weight units="g">106</weight>
		</photoItem>
		<photoItem>
			<inPhotoCode>B </inPhotoCode>
			<atlasNumber>2</atlasNumber>
			<itemDescription>10" pizza thin base</itemDescription>
			<weight units="g">470</weight>
		</photoItem>
		<photoItem>
			<inPhotoCode>C</inPhotoCode>
			<atlasNumber>3</atlasNumber>
			<itemDescription>7" pizza thin base</itemDescription>
			<weight units="g">229</weight>
		</photoItem>
		<photoItem>
			<inPhotoCode>D </inPhotoCode>
			<atlasNumber>4</atlasNumber>
			<itemDescription>13" pizza thin base</itemDescription>
			<weight units="g">719</weight>
		</photoItem>
		<photoItem>
			<inPhotoCode>B </inPhotoCode>
			<atlasNumber>2</atlasNumber>
			<itemDescription>10" pizza deep pan base</itemDescription>
			<weight units="g">570</weight>
		</photoItem>
		<photoItem>
			<inPhotoCode>C</inPhotoCode>
			<atlasNumber>3</atlasNumber>
			<itemDescription>7" pizza deep pan base</itemDescription>
			<weight units="g">253</weight>
		</photoItem>
		<photoItem>
			<inPhotoCode>D </inPhotoCode>
			<atlasNumber>4</atlasNumber>
			<itemDescription>13" pizza deep pan base</itemDescription>
			<weight units="g">826</weight>
		</photoItem>
		<photoItem>
			<inPhotoCode>B </inPhotoCode>
			<atlasNumber>2</atlasNumber>
			<itemDescription>10" pizza extra topping only</itemDescription>
			<weight units="g">64</weight>
		</photoItem>
		<photoItem>
			<inPhotoCode>C</inPhotoCode>
			<atlasNumber>3</atlasNumber>
			<itemDescription>7" pizza extra topping only</itemDescription>
			<weight units="g">45</weight>
		</photoItem>
		<photoItem>
			<inPhotoCode>D </inPhotoCode>
			<atlasNumber>4</atlasNumber>
			<itemDescription>13" pizza extra topping only</itemDescription>
			<weight units="g">84</weight>
		</photoItem>
	</photo>
	<photo>
		<photoGuideCode>G4</photoGuideCode>
		<photoNumber>82</photoNumber>
		<photoFilename>82_G4.jpg</photoFilename>
		<photoDescription>Ham</photoDescription>
		<photoItem>
			<inPhotoCode>A </inPhotoCode>
			<atlasNumber>1</atlasNumber>
			<itemDescription>Sandwich ham</itemDescription>
			<weight units="g">31</weight>
		</photoItem>
		<photoItem>
			<inPhotoCode>B </inPhotoCode>
			<atlasNumber>2</atlasNumber>
			<itemDescription>(ooked ham</itemDescription>
			<weight units="g">17</weight>
		</photoItem>
		<photoItem>
			<inPhotoCode>C</inPhotoCode>
			<atlasNumber>3</atlasNumber>
			<itemDescription>Premium English ham</itemDescription>
			<weight units="g">40</weight>
		</photoItem>
		<photoItem>
			<inPhotoCode>D </inPhotoCode>
			<atlasNumber>4</atlasNumber>
			<itemDescription>Tender sweet roast ham</itemDescription>
			<weight units="g">24</weight>
		</photoItem>
		<photoItem>
			<inPhotoCode>E </inPhotoCode>
			<atlasNumber>5</atlasNumber>
			<itemDescription>Oak smoked ham</itemDescription>
			<weight units="g">16</weight>
		</photoItem>
		<photoItem>
			<inPhotoCode>F </inPhotoCode>
			<atlasNumber>6</atlasNumber>
			<itemDescription>Premium English ham</itemDescription>
			<weight units="g">41</weight>
		</photoItem>
		<photoItem>
			<inPhotoCode>G </inPhotoCode>
			<atlasNumber>7</atlasNumber>
